version: '3.8'
services:
  postgres-db:
    image: postgres:15  # Официальный образ PostgreSQL версии 15
    environment:
      POSTGRES_USER: postgres  # Имя пользователя
      POSTGRES_PASSWORD: postgres  # Пароль пользователя
      POSTGRES_DB: querydsl_demo  # Имя создаваемой базы данных
    ports:
      - "5432:5432"  # Пробрасываем порт 5432 для доступа с хоста
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Хранение данных

volumes:
  postgres_data:  # Том для постоянного хранения данных