spring:
  application:
    name: query-dsl-demo-project

  datasource:
    url: jdbc:postgresql://localhost:5432/querydsl_demo
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update